insert into reference.driver_license (code)
values ('A1'),
       ('A'),
       ('B1'),
       ('B'),
       ('BE'),
       ('C1'),
       ('C1E'),
       ('C'),
       ('CE'),
       ('D1'),
       ('D1E'),
       ('D'),
       ('DE'),
       ('Tm'),
       ('Tb');